version: '3'

services:
  testmysql:
    image: mysql:5.7
    environment:
      PROJECT: ${PROJECT_ID}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: urlmap
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    platform: 'linux/amd64'
    volumes:
      - /var/tmp/mysql:/var/lib/mysql
    ports:
    - 3306:3306
  main:
    build: ../
    environment: 
      PROJECT: ${PROJECT_ID}
      DBUSER: ${MYSQL_USER}
      DBNAME: ${MYSQL_DATABASE}
      DBPASS: ${MYSQL_PASSWORD}
      DBHOST: testmysql
      PORT: 8080
    ports:
    - 8080:8080
  debug:
    build: ./