apiVersion: external-secrets.io/v1alpha1
kind: SecretStore
metadata:
  name: gcp-external-secret
spec:
  provider:
      gcpsm:                                                  
        auth:
          workloadIdentity:
            clusterLocation: us-central1-c
            clusterName: $CLUSTER
            serviceAccountRef:
              name: external-secrets
              namespace: external-secrets
        projectID: $PROJECT
---
apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: gcp-external-secret
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: SecretStore
    name: gcp-external-secret
  target:                                                             
    name: secret-params
  data:                                                       
  - secretKey: SLACK_URL
    remoteRef:            
      key: SLACK_URL
  - secretKey: DBUSER
    remoteRef:            
      key: DBUSER
  - secretKey: APPVER
    remoteRef:            
      key: APPVER
