apiVersion: external-secrets.io/v1alpha1
kind: SecretStore
metadata:
  name: gcp-external-secret-store
spec:
  provider:
      gcpsm:                                                  
        auth:
          workloadIdentity:
            clusterLocation: us-central1-c
            clusterName: $CLUSTER
            serviceAccountRef:
              name: external-secret-o
              namespace: urlmap
        projectID: $PROJECT
---
apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: gcp-external-secret
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: SecretStore
    name: gcp-external-secret-store
  target:                                                             
    name: secret-params
  data:                                                       
  - secretKey: URLMAP_API
    remoteRef:
      key: URLMAP_API
  - secretKey: SLACK_URL
    remoteRef:
      key: SLACK_URL
  - secretKey: SLACK_CHANNEL
    remoteRef:
      key: SLACK_CHANNEL
  - secretKey: APPVER
    remoteRef:
      key: APPVER
  - secretKey: DBUSER
    remoteRef:
      key: DBUSER
  - secretKey: DBHOST
    remoteRef:
      key: DBHOST
  - secretKey: DBUSER
    remoteRef:
      key: DBUSER
  - secretKey: DBNAME
    remoteRef:
      key: DBNAME
  - secretKey: DBPASS
    remoteRef:
      key: DBPASS
  - secretKey: myrepo
    remoteRef:
      key: myrepo