apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: my-nginx
  name: my-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-nginx
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: my-nginx
    spec:
      containers:
      - image: nginx
        name: nginx
        env:
        - name: DBUSER
          valueFrom:
            secretKeyRef:
              key: DBUSER
              name: secret-params
        - name: SLACK_URL
          valueFrom:
            secretKeyRef:
              key: SLACK_URL
              name: secret-params
        - name: APPVER
          valueFrom:
            secretKeyRef:
              key: APPVER
              name: secret-params
        resources: {}
        volumeMounts:
        - name: foo
          mountPath: "/foo"
          readOnly: true
      volumes:
      - name: foo
        secret:
          secretName: secret-params
          optional: false # default setting; "mysecret" must exist
status: {}
