apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: secret-params
spec:
  backendType: gcpSecretsManager
  projectId: shingo-ar-proto
  data:
    - key:  URLMAP_API
      name: URLMAP_API
      version: latest
    - key: DBUSER
      name: DBUSER
      version: latest
    - key: DBHOST
      name: DBHOST
      version: latest
    - key: DBPASS
      name: DBPASS
      version: latest
    - key:  myrepo
      name: myrepo
      version: latest
