# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import urlmap_pb2 as urlmap__pb2


class RedirectionStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetInfo = channel.unary_unary(
        '/urlmap.Redirection/GetInfo',
        request_serializer=urlmap__pb2.OrgUrl.SerializeToString,
        response_deserializer=urlmap__pb2.RedirectData.FromString,
        )
    self.SetInfo = channel.unary_unary(
        '/urlmap.Redirection/SetInfo',
        request_serializer=urlmap__pb2.RedirectData.SerializeToString,
        response_deserializer=urlmap__pb2.OrgUrl.FromString,
        )


class RedirectionServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GetInfo(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SetInfo(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_RedirectionServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetInfo': grpc.unary_unary_rpc_method_handler(
          servicer.GetInfo,
          request_deserializer=urlmap__pb2.OrgUrl.FromString,
          response_serializer=urlmap__pb2.RedirectData.SerializeToString,
      ),
      'SetInfo': grpc.unary_unary_rpc_method_handler(
          servicer.SetInfo,
          request_deserializer=urlmap__pb2.RedirectData.FromString,
          response_serializer=urlmap__pb2.OrgUrl.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'urlmap.Redirection', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
